name = "UniverseMC"
author = "karolkuter-boop"
version = "1.51.06"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7e74c619eb32b58ab683e60773a7535510003534f95d7bbe0fd663d68606d8ca"

[versions]
minecraft = "26.1.2"
neoforge = "26.1.2.75"
