name = "UniverseMC"
author = "karolkuter-boop"
version = "1.17.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f7bd2bd2ba968efff4aaaa2775f8cd7f312c68f1b35331c2e7540c83a275a879"

[versions]
minecraft = "26.1.2"
neoforge = "26.1.2.73"
