#This file stores configuration options for Iris, such as the currently active shaderpack
#Wed Jun 17 19:49:32 CEST 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=MCVHSV2DLRV.zip
